package plan_test

import (
	"fmt"
	"testing"
	"time"

	"github.com/ArjenSchwarz/flux/internal/derivedstats"
	"github.com/ArjenSchwarz/flux/internal/plan"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"pgregory.net/rapid"
)

// This file lives in package plan_test because the integral invariant below
// pairs the plan package with derivedstats. Both are leaf packages, so the
// pairing exists only in the test binary — plan itself still imports nothing
// from Flux.

var sydney = func() *time.Location {
	loc, err := time.LoadLocation("Australia/Sydney")
	if err != nil {
		panic(err)
	}
	return loc
}()

// genPlan draws a plan with 0–4 non-overlapping windows, at most one of them
// free. Windows are generated by walking the day forward so the result is
// always valid — the properties are about Segments, not about validation.
func genPlan(t *rapid.T) plan.Plan {
	n := rapid.IntRange(0, 4).Draw(t, "windowCount")
	freeIndex := rapid.IntRange(-1, n-1).Draw(t, "freeIndex")

	windows := make([]plan.Window, 0, n)
	cursor := 0
	for i := range n {
		// Leave room for the remaining windows so the walk never runs off
		// the end of the day.
		remaining := n - i
		gap := rapid.IntRange(0, 60).Draw(t, fmt.Sprintf("gap%d", i))
		start := cursor + gap
		maxStart := 24*60 - remaining
		if start > maxStart {
			break
		}
		width := rapid.IntRange(1, 24*60-start-(remaining-1)).Draw(t, fmt.Sprintf("width%d", i))
		windows = append(windows, plan.Window{
			Start: plan.FormatBandTime(start),
			End:   plan.FormatBandTime(start + width),
			Free:  i == freeIndex,
			Rate:  float64(rapid.IntRange(0, 10000).Draw(t, fmt.Sprintf("rate%d", i))) / 10000,
		})
		cursor = start + width
	}

	savings := 0.35
	return plan.Plan{
		StartDate:      "2026-01-01",
		DefaultRate:    float64(rapid.IntRange(0, 10000).Draw(t, "defaultRate")) / 10000,
		Windows:        windows,
		FeedInRate:     0.05,
		SavingsRefRate: &savings,
	}
}

// TestPropertySegmentsTileTheDay asserts the core invariant of AC 1.1: the
// derived segments are contiguous, non-overlapping, and cover 00:00–24:00
// exactly, whatever windows the plan carries.
func TestPropertySegmentsTileTheDay(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		segs := plan.Segments(genPlan(t))
		require.NotEmpty(t, segs)

		cursor := 0
		for i, seg := range segs {
			start, okStart := plan.ParseBandTime(seg.Start)
			end, okEnd := plan.ParseBandTime(seg.End)
			require.True(t, okStart, "segment %d start %q must parse", i, seg.Start)
			require.True(t, okEnd, "segment %d end %q must parse", i, seg.End)
			assert.Equal(t, cursor, start, "segment %d must abut its predecessor", i)
			assert.Greater(t, end, start, "segment %d must be non-empty", i)
			cursor = end
		}
		assert.Equal(t, 24*60, cursor, "segments must reach end of day")
	})
}

// TestPropertySegmentsPreserveWindows asserts that every window survives
// segmentation with its rate and free flag intact — the default rate only
// fills what the windows leave uncovered.
func TestPropertySegmentsPreserveWindows(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		p := genPlan(t)
		byRange := make(map[string]plan.Segment)
		for _, seg := range plan.Segments(p) {
			byRange[seg.Start+"-"+seg.End] = seg
		}
		for _, w := range p.Windows {
			seg, ok := byRange[w.Start+"-"+w.End]
			require.True(t, ok, "window %s-%s must appear as a segment", w.Start, w.End)
			assert.Equal(t, w.Free, seg.Free)
			if !w.Free {
				assert.Equal(t, w.Rate, seg.Rate)
			}
		}
	})
}

// TestPropertySegmentsNotMerged asserts Q26: abutting segments carrying the
// same rate stay separate, so the stored bandImports geometry is stable.
func TestPropertySegmentsNotMerged(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		p := genPlan(t)
		// Force every window onto the default rate so any merging would be
		// visible as a shorter segment list.
		for i := range p.Windows {
			p.Windows[i].Free = false
			p.Windows[i].Rate = p.DefaultRate
		}
		segs := plan.Segments(p)
		for _, w := range p.Windows {
			found := false
			for _, seg := range segs {
				if seg.Start == w.Start && seg.End == w.End {
					found = true
					break
				}
			}
			assert.True(t, found, "same-rate window %s-%s must stay its own segment", w.Start, w.End)
		}
	})
}

// genReadings draws readings spanning a full local calendar day, including
// the DST-length days, at 30–120 s spacing so the integrator's 60 s pair-gap
// rule sees a mixture of usable and skipped pairs.
func genReadings(t *rapid.T, day time.Time) []derivedstats.Reading {
	end := time.Date(day.Year(), day.Month(), day.Day()+1, 0, 0, 0, 0, sydney).Unix()
	readings := make([]derivedstats.Reading, 0, 3000)
	ts := day.Unix()
	for ts < end {
		readings = append(readings, derivedstats.Reading{
			Timestamp: ts,
			Pgrid:     rapid.Float64Range(-5000, 5000).Draw(t, fmt.Sprintf("pgrid%d", len(readings))),
		})
		ts += int64(rapid.IntRange(30, 120).Draw(t, fmt.Sprintf("gap%d", len(readings))))
	}
	return readings
}

// TestPropertySegmentIntegralsSumToWholeDay is the AC 3.8 invariant: summing
// the per-segment grid-import integrals reproduces the whole-day integral,
// because SegmentBounds derives shared wall-clock boundaries that cancel
// pairwise. It runs on ordinary, 23-hour, and 25-hour Sydney days — the case
// dayStart.Add(elapsed) arithmetic would get wrong.
func TestPropertySegmentIntegralsSumToWholeDay(t *testing.T) {
	dates := []string{"2026-04-12", "2026-04-05", "2026-10-04"}
	for _, date := range dates {
		t.Run(date, func(t *testing.T) {
			day, err := time.ParseInLocation("2006-01-02", date, sydney)
			require.NoError(t, err)
			rapid.Check(t, func(t *rapid.T) {
				p := genPlan(t)
				readings := genReadings(t, day)
				segs := plan.Segments(p)

				whole := plan.Segment{Start: "00:00", End: "24:00"}
				dayFrom, dayTo := plan.SegmentBounds(whole, day, sydney)
				total, ok := derivedstats.IntegrateOffpeakDeltas(readings, dayFrom, dayTo)
				if !ok {
					return
				}

				var summed float64
				for _, seg := range segs {
					from, to := plan.SegmentBounds(seg, day, sydney)
					part, partOK := derivedstats.IntegrateOffpeakDeltas(readings, from, to)
					if !partOK {
						// A segment too short to hold two construction points
						// contributes nothing; the whole-day integral loses the
						// same slice, so the comparison would be meaningless.
						return
					}
					summed += part.GridImportKwh
				}
				assert.InDelta(t, total.GridImportKwh, summed, 1e-9)
			})
		})
	}
}

// TestPropertyPlanForPicksExactlyOnePlan asserts AC 2.1 across a generated
// succession chain: consecutive plans whose end date is the next plan's start
// date price every day in the chain exactly once, with the switch day always
// going to the successor.
func TestPropertyPlanForPicksExactlyOnePlan(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		start, err := time.ParseInLocation("2006-01-02", "2026-01-01", sydney)
		require.NoError(t, err)

		n := rapid.IntRange(1, 5).Draw(t, "planCount")
		plans := make([]plan.Plan, 0, n)
		boundaries := []time.Time{start}
		cursor := start
		for i := range n {
			cursor = cursor.AddDate(0, 0, rapid.IntRange(1, 400).Draw(t, fmt.Sprintf("span%d", i)))
			boundaries = append(boundaries, cursor)
			p := plan.Plan{
				ID:        fmt.Sprintf("p%d", i),
				StartDate: boundaries[i].Format("2006-01-02"),
				EndDate:   cursor.Format("2006-01-02"),
			}
			plans = append(plans, p)
		}
		// The last plan is open-ended, matching the single-open-ended rule.
		plans[len(plans)-1].EndDate = ""

		for i, p := range plans {
			// A plan owns its own start date...
			got, ok := plan.PlanFor(plans, p.StartDate)
			require.True(t, ok, "plan %d start date must be priced", i)
			assert.Equal(t, p.ID, got.ID)

			// ...and the day before it belongs to the predecessor, never to it.
			eve := boundaries[i].AddDate(0, 0, -1).Format("2006-01-02")
			if prev, prevOK := plan.PlanFor(plans, eve); prevOK {
				assert.NotEqual(t, p.ID, prev.ID, "switch day eve must belong to the predecessor")
			}
		}

		// No day is priced twice: at most one plan covers any date.
		day := start
		for day.Before(cursor.AddDate(0, 0, 2)) {
			date := day.Format("2006-01-02")
			matches := 0
			for _, p := range plans {
				if p.Covers(date) {
					matches++
				}
			}
			assert.LessOrEqual(t, matches, 1, "date %s priced by %d plans", date, matches)
			day = day.AddDate(0, 0, rapid.IntRange(1, 90).Draw(t, "step"))
		}
	})
}

// TestPropertyFreeWindowMatchesSegments asserts FreeWindow and Segments agree:
// when a plan has a free band, the reported window is exactly the free
// segment's span.
func TestPropertyFreeWindowMatchesSegments(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		p := genPlan(t)
		p.StartDate = "2026-01-01"
		startMin, endMin, ok := plan.FreeWindow([]plan.Plan{p}, "2026-06-01")

		var free *plan.Segment
		for _, seg := range plan.Segments(p) {
			if seg.Free {
				free = &seg
				break
			}
		}
		if free == nil {
			assert.False(t, ok)
			return
		}
		require.True(t, ok)
		wantStart, _ := plan.ParseBandTime(free.Start)
		wantEnd, _ := plan.ParseBandTime(free.End)
		assert.Equal(t, wantStart, startMin)
		assert.Equal(t, wantEnd, endMin)
	})
}
